import 'package:winit_agent/core/data/enum/environment.dart';
import 'env/env.dart';

class AppConfig {
  static late Map<String, dynamic> _config;
  static late Environment _currentEnv;

  static void setEnvironment(Environment env) {
    _currentEnv = env;
    switch (env) {
      case Environment.dev:
        _config = _BaseUrlConfig.debugConstants;
        break;
      case Environment.staging:
        _config = _BaseUrlConfig.stagingConstants;
        break;
      case Environment.prod:
        _config = _BaseUrlConfig.prodConstants;
        break;
      case Environment.qa:
        _config = _BaseUrlConfig.qaConstants;
        break;
    }
  }

  static Environment get currentEnvironment => _currentEnv;

  static String get baseUrl => _config[_BaseUrlConfig.baseUrl];

  static String get payStackKey => _config[_BaseUrlConfig.payStackKey];

  // You can also add direct access for common routes here
  static String get authRoute => Env.auth;
  static String get clientId => _currentEnv == Environment.prod ? Env.clientId : Env.clientIdStaging;
}

class _BaseUrlConfig {
  static const baseUrl = 'BaseUrl';
  static const payStackKey = 'PayStackPublicKey';

  // We point directly to the Env class generated by Envied
  static Map<String, dynamic> debugConstants = {
    baseUrl: Env.debugBaseUrl,
    payStackKey: Env.debugPaystackKey,
  };

  static Map<String, dynamic> stagingConstants = {
    baseUrl: Env.stagingBaseUrl,
    payStackKey: Env.stagingPaystackKey,
  };

  static Map<String, dynamic> qaConstants = {
    baseUrl: Env.qaBaseUrl,
    payStackKey: Env.qaPaystackKey,
  };

  static Map<String, dynamic> prodConstants = {
    baseUrl: Env.prodBaseUrl,
    payStackKey: Env.prodPaystackKey,
  };
}

// class AppConfig {
//   static late Map<String, dynamic> _config;
//   static late Environment _currentEnv;
//
//   static void setEnvironment(Environment env) {
//     _currentEnv = env;
//     switch (env) {
//       case Environment.dev:
//         _config = _BaseUrlConfig.debugConstants;
//         break;
//       case Environment.staging:
//         _config = _BaseUrlConfig.stagingConstants;
//         break;
//       case Environment.prod:
//         _config = _BaseUrlConfig.prodConstants;
//         break;
//       case Environment.qa:
//         _config = _BaseUrlConfig.qaConstants;
//         break;
//     }
//   }
//
//   static Environment get currentEnvironment => _currentEnv;
//
//   static get baseUrl {
//     return _config[_BaseUrlConfig.baseUrl];
//   }
//
//   static get payStackKey {
//     return _config[_BaseUrlConfig.payStackKey];
//   }
// }
//
// class _BaseUrlConfig {
//   static const baseUrl = 'BaseUrl';
//   static const payStackKey = 'PayStackPublicKey';
//
//   static Map<String, dynamic> debugConstants = {
//     baseUrl: dotenv.env['DEBUG_BASE_URL'],
//     payStackKey: dotenv.env['DEBUG_PAY_STACK_KEY'],
//   };
//
//   static Map<String, dynamic> stagingConstants = {
//     baseUrl: dotenv.env['STAGING_BASE_URL'],
//     payStackKey: dotenv.env['STAGING_PAY_STACK_KEY'],
//   };
//
//   static Map<String, dynamic> qaConstants = {
//     baseUrl: dotenv.env['QA_BASE_URL'],
//     payStackKey: dotenv.env['QA_PAY_STACK_KEY'],
//   };
//
//   static Map<String, dynamic> prodConstants = {
//     baseUrl: dotenv.env['PROD_BASE_URL'],
//     payStackKey: dotenv.env['PROD_PAY_STACK_KEY'],
//   };
//
// }
